apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "invoice-frontend-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: invoice-frontend
  template:
    metadata:
      labels:
        app: invoice-frontend
    spec:
      containers:
        - name: invoice-frontend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
