apiVersion: v1
kind: Service
metadata:
  name: {{ include "invoice-frontend-chart.fullname" . }}
spec:
  selector:
    app: invoice-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
  type: {{ .Values.service.type }}
